python main.py  ./CWE-20/test_prompt.txt --model distilroberta --output ./CWE-20/test_dir.csv --cwe CWE-20
python main.py  ./CWE-20/test_prompt.txt --model minilm --output ./CWE-20/test_minilm_out.csv --cwe CWE-20
python main.py  ./CWE-20/test_prompt.txt --model mpnet --output ./CWE-20/test_mpnet_out.csv --cwe CWE-20
python main.py  ./CWE-22/test_prompt.txt --model distilroberta --output ./CWE-22/test_dir.csv --cwe CWE-22
python main.py  ./CWE-22/test_prompt.txt --model minilm --output ./CWE-22/test_minilm_out.csv --cwe CWE-22
python main.py  ./CWE-22/test_prompt.txt --model mpnet --output ./CWE-22/test_mpnet_out.csv --cwe CWE-22
python main.py  ./CWE-78/test_prompt.txt --model distilroberta --output ./CWE-78/test_dir.csv --cwe CWE-78
python main.py  ./CWE-78/test_prompt.txt --model minilm --output ./CWE-78/test_minilm_out.csv --cwe CWE-78
python main.py  ./CWE-78/test_prompt.txt --model mpnet --output ./CWE-78/test_mpnet_out.csv --cwe CWE-78
python main.py  ./CWE-79/test_prompt.txt --model distilroberta --output ./CWE-79/test_dir.csv --cwe CWE-79
python main.py  ./CWE-79/test_prompt.txt --model minilm --output ./CWE-79/test_minilm_out.csv --cwe CWE-79
python main.py  ./CWE-79/test_prompt.txt --model mpnet --output ./CWE-79/test_mpnet_out.csv --cwe CWE-79
python main.py  ./CWE-89/test_prompt.txt --model distilroberta --output ./CWE-89/test_dir.csv --cwe CWE-89
python main.py  ./CWE-89/test_prompt.txt --model minilm --output ./CWE-89/test_minilm_out.csv --cwe CWE-89
python main.py  ./CWE-89/test_prompt.txt --model mpnet --output ./CWE-89/test_mpnet_out.csv --cwe CWE-89
python main.py  ./CWE-200/test_prompt.txt --model distilroberta --output ./CWE-200/test_dir.csv --cwe CWE-200
python main.py  ./CWE-200/test_prompt.txt --model minilm --output ./CWE-200/test_minilm_out.csv --cwe CWE-200
python main.py  ./CWE-200/test_prompt.txt --model mpnet --output ./CWE-200/test_mpnet_out.csv --cwe CWE-200
python main.py  ./CWE-306/test_prompt.txt --model distilroberta --output ./CWE-306/test_dir.csv --cwe CWE-306
python main.py  ./CWE-306/test_prompt.txt --model minilm --output ./CWE-306/test_minilm_out.csv --cwe CWE-306
python main.py  ./CWE-306/test_prompt.txt --model mpnet --output ./CWE-306/test_mpnet_out.csv --cwe CWE-306
python main.py  ./CWE-434/test_prompt.txt --model distilroberta --output ./CWE-434/test_dir.csv --cwe CWE-434
python main.py  ./CWE-434/test_prompt.txt --model minilm --output ./CWE-434/test_minilm_out.csv --cwe CWE-434
python main.py  ./CWE-434/test_prompt.txt --model mpnet --output ./CWE-434/test_mpnet_out.csv --cwe CWE-434
python main.py  ./CWE-502/test_prompt.txt --model distilroberta --output ./CWE-502/test_dir.csv --cwe CWE-502
python main.py  ./CWE-502/test_prompt.txt --model minilm --output ./CWE-502/test_minilm_out.csv --cwe CWE-502
python main.py  ./CWE-502/test_prompt.txt --model mpnet --output ./CWE-502/test_mpnet_out.csv --cwe CWE-502
python main.py  ./CWE-522/test_prompt.txt --model distilroberta --output ./CWE-522/test_dir.csv --cwe CWE-522
python main.py  ./CWE-522/test_prompt.txt --model minilm --output ./CWE-522/test_minilm_out.csv --cwe CWE-522
python main.py  ./CWE-522/test_prompt.txt --model mpnet --output ./CWE-522/test_mpnet_out.csv --cwe CWE-522
python main.py  ./CWE-732/test_prompt.txt --model distilroberta --output ./CWE-732/test_dir.csv --cwe CWE-732
python main.py  ./CWE-732/test_prompt.txt --model minilm --output ./CWE-732/test_minilm_out.csv --cwe CWE-732
python main.py  ./CWE-732/test_prompt.txt --model mpnet --output ./CWE-732/test_mpnet_out.csv --cwe CWE-732
python main.py  ./CWE-798/test_prompt.txt --model distilroberta --output ./CWE-798/test_dir.csv --cwe CWE-798
python main.py  ./CWE-798/test_prompt.txt --model minilm --output ./CWE-798/test_minilm_out.csv --cwe CWE-798
python main.py  ./CWE-798/test_prompt.txt --model mpnet --output ./CWE-798/test_mpnet_out.csv --cwe CWE-798
python main.py  ./validation_test/validation_prompt.txt --model distilroberta --output ./validation_test/dir_out.csv --cwe CWE-798
python main.py  ./validation_test/validation_prompt.txt --model minilm --output ./validation_test/minilm_out.csv --cwe CWE-798
python main.py  ./validation_test/validation_prompt.txt --model mpnet --output ./validation_test/mpnet_out.csv --cwe CWE-798